### ISSUE TITLE
local reference table overflow

### ISSUE THREAD

**Issue by uusoftware** [vincentjames501/libvorbis-libogg-android#16]
Hi! When I started to record, after a while app crashes. I don't change anything just import this project and run on Samsung Note 2. Here is the logcat logs:

07-30 15:26:14.526: D/dalvikvm(16779): Trying to load lib /data/app-lib/com.vorbisdemo-1/libogg.so 0x421c44d8
07-30 15:26:14.531: D/dalvikvm(16779): Added shared lib /data/app-lib/com.vorbisdemo-1/libogg.so 0x421c44d8
07-30 15:26:14.531: D/dalvikvm(16779): No JNI_OnLoad found in /data/app-lib/com.vorbisdemo-1/libogg.so 0x421c44d8, skipping init
07-30 15:26:14.531: D/dalvikvm(16779): Trying to load lib /data/app-lib/com.vorbisdemo-1/libvorbis.so 0x421c44d8
07-30 15:26:14.536: D/dalvikvm(16779): Added shared lib /data/app-lib/com.vorbisdemo-1/libvorbis.so 0x421c44d8
07-30 15:26:14.536: D/dalvikvm(16779): No JNI_OnLoad found in /data/app-lib/com.vorbisdemo-1/libvorbis.so 0x421c44d8, skipping init
07-30 15:26:14.541: D/dalvikvm(16779): Trying to load lib /data/app-lib/com.vorbisdemo-1/libvorbis-jni.so 0x421c44d8
07-30 15:26:14.541: D/dalvikvm(16779): Added shared lib /data/app-lib/com.vorbisdemo-1/libvorbis-jni.so 0x421c44d8
07-30 15:26:14.541: D/dalvikvm(16779): No JNI_OnLoad found in /data/app-lib/com.vorbisdemo-1/libvorbis-jni.so 0x421c44d8, skipping init
07-30 15:26:14.541: I/VorbisEncoder(16779): Setting up encoding
07-30 15:26:14.541: I/VorbisEncoder(16779): Initializing with 2 channels 44100Hz sample rate and 1.000000 quality
07-30 15:26:14.541: I/VorbisEncoder(16779): Notifying encode feed to start
07-30 15:26:14.886: D/VorbisEncoder(16779): Adding comments
07-30 15:26:14.976: I/VorbisEncoder(16779): Writting header
07-30 15:26:14.976: I/VorbisEncoder(16779): Starting to read from pcm callback
07-30 15:26:36.246: D/dalvikvm(16779): GC_FOR_ALLOC freed 101K, 12% free 9731K/11000K, paused 34ms, total 34ms
07-30 15:26:37.206: E/dalvikvm(16779): JNI ERROR (app bug): local reference table overflow (max=512)
07-30 15:26:37.206: W/dalvikvm(16779): JNI local reference table (0x5cc947e0) dump:
07-30 15:26:37.206: W/dalvikvm(16779):   Last 10 entries (of 512):
07-30 15:26:37.206: W/dalvikvm(16779):       511: 0x4192f290 libcore.io.Posix
07-30 15:26:37.206: W/dalvikvm(16779):       510: 0x423de5e0 byte[] (5025 elements)
07-30 15:26:37.206: W/dalvikvm(16779):       509: 0x42265cb0 byte[] (49 elements)
07-30 15:26:37.206: W/dalvikvm(16779):       508: 0x423dd0d8 byte[] (5362 elements)
07-30 15:26:37.206: W/dalvikvm(16779):       507: 0x4226a888 byte[] (51 elements)
07-30 15:26:37.206: W/dalvikvm(16779):       506: 0x423dbba8 byte[] (5398 elements)
07-30 15:26:37.206: W/dalvikvm(16779):       505: 0x4226f468 byte[] (51 elements)
07-30 15:26:37.206: W/dalvikvm(16779):       504: 0x423da680 byte[] (5393 elements)
07-30 15:26:37.211: W/dalvikvm(16779):       503: 0x42274108 byte[] (51 elements)
07-30 15:26:37.211: W/dalvikvm(16779):       502: 0x423d9170 byte[] (5366 elements)
07-30 15:26:37.211: W/dalvikvm(16779):   Summary:
07-30 15:26:37.211: W/dalvikvm(16779):         2 of java.lang.Class (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (28 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (30 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (44 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         5 of byte[] (45 elements) (5 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):        17 of byte[] (46 elements) (17 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (47 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         9 of byte[] (48 elements) (9 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         8 of byte[] (49 elements) (8 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):        14 of byte[] (50 elements) (14 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):       195 of byte[] (51 elements) (195 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (3997 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4096 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4108 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (4110 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4127 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4159 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4258 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4264 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (4290 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4318 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4332 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4339 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4349 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4352 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4358 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4360 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4385 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4390 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4398 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4413 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4439 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4518 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4527 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4646 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4668 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4701 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4749 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (4816 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4828 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4837 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4856 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4946 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4973 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4982 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (4999 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5025 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5049 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5118 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5123 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5162 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5179 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5188 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5206 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5231 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5264 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5276 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5284 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5285 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5288 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5290 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5291 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5293 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5294 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5295 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5297 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5299 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5300 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5301 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5303 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5304 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5305 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5306 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5308 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5309 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5310 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5311 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5312 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5313 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5314 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5315 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5316 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5317 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5318 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5319 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5320 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5321 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5322 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5323 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5324 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         4 of byte[] (5326 elements) (4 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5327 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5328 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5329 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5330 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5331 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5332 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5333 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5334 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5335 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5336 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         4 of byte[] (5337 elements) (4 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5338 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5339 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5340 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5341 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5342 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5343 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         4 of byte[] (5344 elements) (4 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5346 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         5 of byte[] (5347 elements) (5 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5349 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5350 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5351 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         4 of byte[] (5352 elements) (4 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5354 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5355 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         7 of byte[] (5356 elements) (7 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5357 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5358 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5359 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         4 of byte[] (5360 elements) (4 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5362 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5363 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5366 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5367 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5368 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5369 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5370 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5371 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5374 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5375 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5376 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         4 of byte[] (5377 elements) (4 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5378 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5379 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5380 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5383 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         3 of byte[] (5384 elements) (3 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5385 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5386 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5388 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5389 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5390 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5393 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5394 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         2 of byte[] (5396 elements) (2 unique instances)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5398 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5400 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5401 elements)
07-30 15:26:37.211: W/dalvikvm(16779):         1 of byte[] (5402 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5404 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         2 of byte[] (5407 elements) (2 unique instances)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5409 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5411 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5412 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5413 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5414 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5416 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5417 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5421 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5424 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5446 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5457 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5467 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5468 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5477 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5508 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         2 of byte[] (5533 elements) (2 unique instances)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5537 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5582 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (5671 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of byte[] (8192 elements)
07-30 15:26:37.216: W/dalvikvm(16779):         1 of libcore.io.Posix
07-30 15:26:37.216: W/dalvikvm(16779):         1 of org.xiph.vorbis.recorder.VorbisRecorder$FileEncodeFeed
07-30 15:26:37.216: E/dalvikvm(16779): Failed adding to JNI local ref table (has 512 entries)
07-30 15:26:37.216: I/dalvikvm(16779): "Thread-4746" prio=5 tid=12 RUNNABLE
07-30 15:26:37.216: I/dalvikvm(16779):   | group="main" sCount=0 dsCount=0 obj=0x42295e08 self=0x5cefe5d8
07-30 15:26:37.216: I/dalvikvm(16779):   | sysTid=16799 nice=-19 sched=0/0 cgrp=apps handle=1559226928
07-30 15:26:37.216: I/dalvikvm(16779):   | state=R schedstat=( 8261721178 170829344 3449 ) utm=795 stm=31 core=3
07-30 15:26:37.216: I/dalvikvm(16779):   at libcore.io.Posix.writeBytes(Native Method)
07-30 15:26:37.216: I/dalvikvm(16779):   at libcore.io.Posix.write(Posix.java:202)
07-30 15:26:37.216: I/dalvikvm(16779):   at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
07-30 15:26:37.216: I/dalvikvm(16779):   at libcore.io.IoBridge.write(IoBridge.java:450)
07-30 15:26:37.216: I/dalvikvm(16779):   at java.io.FileOutputStream.write(FileOutputStream.java:187)
07-30 15:26:37.221: I/dalvikvm(16779):   at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
07-30 15:26:37.221: I/dalvikvm(16779):   at java.io.BufferedOutputStream.write(BufferedOutputStream.java:139)
07-30 15:26:37.221: I/dalvikvm(16779):   at org.xiph.vorbis.recorder.VorbisRecorder$FileEncodeFeed.writeVorbisData(VorbisRecorder.java:182)
07-30 15:26:37.221: I/dalvikvm(16779):   at org.xiph.vorbis.encoder.VorbisEncoder.startEncodingWithQuality(Native Method)
07-30 15:26:37.221: I/dalvikvm(16779):   at org.xiph.vorbis.recorder.VorbisRecorder$AsyncEncoding.run(VorbisRecorder.java:512)
07-30 15:26:37.221: I/dalvikvm(16779):   at java.lang.Thread.run(Thread.java:841)
07-30 15:26:37.221: E/dalvikvm(16779): VM aborting
07-30 15:26:37.221: A/libc(16779): Fatal signal 6 (SIGABRT) at 0x0000418b (code=-6), thread 16799 (Thread-4746)

**Comment by sajadmartiny** [comment]
hi,The project gives me the same error
12-23 17:14:08.730 30371-31808/com.example.idek_2.testogg E/dalvikvm: JNI ERROR (app bug): local reference table overflow (max=512)
12-23 17:14:08.767 30371-31808/com.example.idek_2.testogg E/dalvikvm: Failed adding to JNI local ref table (has 512 entries)
12-23 17:14:08.781 30371-31808/com.example.idek_2.testogg E/dalvikvm: VM aborting
12-23 17:14:08.782 30371-31808/com.example.idek_2.testogg A/libc: Fatal signal 6 (SIGABRT) at 0x000076a3 (code=-6), thread 31808 (Thread-142904)

pls,help

**Comment by alexcohn** [comment]
I believe that in [line 45](https://github.com/vincentjames501/libvorbis-libogg-android/blob/master/jni/libvorbis-jni/org_xiph_vorbis_encoder_VorbisEncoder.c#L45) the call

    (*env)->DeleteLocalRef(env, (*jByteArrayBuffer));

should be added. 

A similar fix was made in a [recent commit](https://github.com/vincentjames501/libvorbis-libogg-android/commit/18e49d55d66bc295d8ef835d906d757908d5f0e1#diff-14780fb01dc7b653aaa48547d7810e1f) for **writeVorbisDataToEncoderDataFeed()**.
